# Generated by Django 5.1.7 on 2025-04-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='place',
        ),
        migrations.AddField(
            model_name='task',
            name='Employee',
            field=models.ManyToManyField(to='api.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='place',
            field=models.ManyToManyField(to='api.place'),
        ),
    ]
