# Generated by Django 5.1.7 on 2025-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_employee_task_employee_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
