# Generated by Django 5.1.7 on 2025-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tarea_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
