# Generated by Django 5.1.7 on 2025-04-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tarea_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excusa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fromDate', models.CharField(max_length=50)),
                ('toDate', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
